---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ci-triage-secrets
  namespace: ci-triage
spec:
  encryptedData:
    OPENROUTER_API_KEY: AgBUGvPdrLJVcCkknhws8WVdZIb3OH1uuAZtirg0dI/ZyhDO8logiKW5eXGG0CmDSTNd6UCSq4B4Ym3pzFj2je9DCWVrIQT3GuUxdHQUurTZzew/3SLu3oBEV3hoJa75QvoyvzLw3moE9tNNt3haaXCDg8hZyWj/TZkdjtJ2EJ0m1PwsxEkZnEjUSjyVEWHR0MjrGVezaV+2thPPGGJTKaGoDIIxZ24HeTFpFkTJ7tfor4sGRBc+ThCXHdsoTUR12ors/TsJl5cZIYM+EDKw0mXpVnkUio8s8iviffYHuoMF7WT7kWfQRqQ+lhlWdq5Fndv6099K7KeYgk2Wj7Fh85TDudvSHTpM90pkKsDONwPRI8DCN2VLSTkm47GuKPKMv/xVFLN8MYyvryZMay058JZ2ogc6Fw3QOw2FLUBkRY5yQun0eqwbCWkJjXEjODhseZx9zCBYs+Hik01rODBmhQPxUnKPy64pc5+hvHbR3mpbi7arcAIy17FUEbjcbBFim/J9SjzpVrJ6l0rAoyeDjks9kanrrB2gRn+kPHwVO31GoiSiRUGlLkWCx6nhOD9Sy2zNar05u8jwjBkvQHC56Y+rDaMwWzUsJ7DNu3xtNlOeUVvkuHKzyTNWhEmm19Zlt8am+wdoipBrqLXk+oRaj0xV24nxRoaXWrvh1Blxv09QxQCpIn8gZT6C99p9UxNYMczSP70Omxofha/y56NhS0fv/rOeAwRx8FauzJZgFfYcXCiaCyzpajr2CLcBiwhPWYsOR5MHFsdPYFWbloTYxDT725lVDWqzy00Y
  template:
    metadata:
      name: ci-triage-secrets
      namespace: ci-triage
